// vue-app/src/views/products/product-list.vue
<script>
import CardContent from '@/components/card-content.vue';

const captains = console;

export default {
  name: 'ProductList',
  props: {
    products: {
      type: Array,
      default: () => [],
    },
  },
  components: { CardContent },
  methods: {
    selectProduct(product) {
      captains.log(`You tried to select ${product.name}`);
      this.$emit('selected', product);
    },
  },
};
</script>

<template>
  <div>
    <div v-if="!products.length">Loading data ...</div>
    <ul class="list">
      <li v-for="product in products" :key="product.id" role="presentation">
        <div class="card">
          <CardContent
            :name="product.name"
            :description="product.description"
          />
        </div>
      </li>
    </ul>
  </div>
</template>

// react-app/src/products/ProductList.js
import React from 'react';
import { withRouter } from 'react-router';

import { CardContent } from '../components';

function ProductList({products}) {
  return (
    <div>
      {products.length === 0 && <div>Loading data ...</div>}
      <ul className="list">
        {products.map((product) => (
          <li key={product.id} role="presentation">
            <div className="card">
              <CardContent
                name={product.name}
                description={product.description}
              />
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default withRouter(ProductList);
