// svelte-app/src/products/ProductList.svelte
<script>
  import { CardContent } from '../components';

  export let products = [];
</script>

<div>
  {#if !products.length}
    <div>Loading data ...</div>
  {/if}
  <ul class="list">
    {#each products as { id, name, description }, i (id)}
      <li role="presentation">
        <div class="card">
          <CardContent {name} {description} />
        </div>
      </li>
    {/each}
  </ul>
</div>

// angular-app/src/app/products/product-list.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { Product } from '../core';

@Component({
  selector: 'app-product-list',
  template: `
    <div *ngIf="!products?.length">
      Loading data ...
    </div>
    <ul class="list">
      <li
        role="presentation"
        *ngFor="let product of products; trackBy: trackByProduct; let i = index"
      >
        <div class="card">
          <app-card-content
            [name]="product.name"
            [description]="product.description"
          ></app-card-content>
        </div>
      </li>
    </ul>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductListComponent {
  @Input() products: Product[];

  trackByProduct(index: number, product: Product): number {
    return product.id;
  }
}
